import React from 'react';

export default function Portal() {
    return (
        <div style={{ color: '#424242' }}>
            <p style={{ margin: '0 400px 50px 400px' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a mattis nisl. Donec iaculis ornare nulla, a rutrum diam rhoncus vitae. Proin blandit fringilla libero. Nunc erat ex, auctor eu urna semper, ultrices facilisis lectus. In hac habitasse platea dictumst. Cras sagittis arcu at neque suscipit placerat ac non eros. Donec tempor mattis purus maximus lobortis.</p>
            <p style={{ margin: '0 400px 50px 400px' }}>In eu nunc quis purus egestas fringilla non et lectus. Donec vitae diam neque. Suspendisse molestie magna quis nisl fringilla blandit et at nisl. Sed sed ex sit amet nunc feugiat luctus. Cras nec purus sapien. Nullam tincidunt quam vitae erat vehicula congue. Integer efficitur scelerisque risus sed porta. Suspendisse lacinia condimentum ante, non aliquam nisl sollicitudin id. Sed eget tincidunt sem, ut viverra turpis. Maecenas ut odio tincidunt, mattis tortor et, lacinia nunc.</p>
            <p style={{ margin: '0 400px 50px 400px' }}>Phasellus faucibus risus tellus, eget porttitor neque porttitor et. Ut ut scelerisque sapien. Ut placerat quis massa id finibus. Proin libero mauris, mattis quis feugiat sit amet, viverra eu mi. Etiam ultrices ultricies neque ut lobortis. Integer tortor eros, semper et venenatis vel, ultrices eget mauris. Suspendisse non hendrerit enim, et tincidunt enim. Sed eget nisi nec nibh eleifend imperdiet.</p>
            <div>
                <img src="https://wallpapers.com/images/hd/mercedes-amg-gt3-4k-laptop-car-arofw39j5cfirdoj.jpg" />
            </div>
            <p style={{ margin: '0 400px 50px 400px' }}>Sed mollis rhoncus odio at euismod. Sed interdum accumsan velit ac consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce et imperdiet lacus. Mauris cursus leo id ligula pellentesque iaculis. Praesent arcu dolor, blandit at augue ac, vehicula aliquam ante. Pellentesque facilisis sapien congue quam sodales semper. Pellentesque sed mauris at orci ullamcorper finibus sit amet interdum lorem. Sed eget enim sed mauris scelerisque dictum. Donec ante nisl, faucibus a venenatis eu, accumsan ut risus. Sed placerat risus eu sapien semper sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas aliquam nisi sed sapien posuere, sed consequat ligula maximus.</p>
            <p style={{ margin: '0 400px 50px 400px' }}>Sed quis mauris a lorem fermentum consectetur nec aliquet felis. Nullam mattis diam vitae sagittis tempus. Cras euismod sapien molestie blandit placerat. Donec sollicitudin finibus commodo. Nulla pulvinar arcu eu enim lobortis elementum. Proin posuere arcu nisl, at ullamcorper urna ornare ut. Curabitur leo erat, aliquet at malesuada a, finibus ac sapien. Integer sit amet bibendum arcu, nec tincidunt justo. Curabitur fringilla nunc vitae augue ornare consequat. Fusce vel enim vel mauris interdum vulputate a in augue. Donec at sapien sed nisl sollicitudin dictum id ut nulla. Quisque vitae nibh purus. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
        </div>
    )
}